import assert from 'node:assert/strict';
import {firstInvoice,dayInMonth} from '../dist/finance.mjs';
import {cashSeries,dated,groupAmounts,change,recurringDate} from '../dist/analytics.mjs';
import {interpretMessage} from '../dist/assistant.mjs';
const card={dia_fechamento:4,dia_vencimento:10};
assert.equal(dayInMonth(firstInvoice('2026-10-03',card),10),'2026-10-10');
assert.equal(dayInMonth(firstInvoice('2026-10-04',card),10),'2026-11-10');
assert.deepEqual([0,1,2].map(i=>recurringDate('2027-01-31',i)),['2027-01-31','2027-02-28','2027-03-31']);
const rows=[{tipo:'saida',forma:'credito',valor:100,status:'pendente',data_prevista:'2026-10-10'},{tipo:'pagamento_fatura',forma:'pix',valor:100,status:'concluido',data_realizada:'2026-10-10',data_prevista:'2026-10-10'},{tipo:'transferencia',valor:500,status:'concluido',data_realizada:'2026-10-02',data_prevista:'2026-10-02'},{tipo:'entrada',valor:1000,status:'concluido',data_realizada:'2026-10-02',data_prevista:'2026-10-02'}];
const full=cashSeries(rows,['2026-10'])[0],partial=cashSeries(rows,['2026-10'],5)[0];
assert.equal(full.income,1000);assert.equal(full.expense,100);assert.equal(partial.expense,0);
assert.equal(groupAmounts(dated(rows,'2026-10-01','2026-10-31','due').filter(r=>r.tipo==='saida'),()=> 'Cartão')[0].value,100);
assert.match(change(100,0),/sem base percentual/);
const D={pessoas:[{id:'d',nome:'David'},{id:'c',nome:'Carol'}],contas:[{id:'b',nome:'C6',tipo:'bancaria'}],cartoes:[{id:'i',nome:'Inter Carol'}],categorias:[{id:'s',nome:'Alimentação',tipo:'saida'}],fin_subcategorias:[]};
let r=interpretMessage('Gastei 85 reais no mercado, Pix pelo C6, família',D,'2026-10-01');assert.equal(r.draft.valor,85);assert.equal(r.draft.conta_id,'b');assert.equal(r.draft.pessoa_id,'');assert.equal(r.draft.categoria_id,'s');
r=interpretMessage('Carol comprou roupa por 240 reais em 3 parcelas no cartão Inter, dia 03',D,'2026-10-01');assert.equal(r.draft.valor,240);assert.equal(r.draft.quantidade,3);assert.equal(r.draft.cartao_id,'i');assert.equal(r.draft.data_prevista,'2026-10-03');assert.equal(r.draft.pessoa_id,'c');
r=interpretMessage('Comprei no cartão Inter em 3x de 80 reais',D,'2026-10-01');assert.equal(r.draft.valor,240);assert.equal(r.draft.quantidade,3);
r=interpretMessage('Paguei a fatura do cartão Inter de 03/10',D,'2026-10-01');assert.equal(r.draft.valor,undefined,'date never becomes money');assert.equal(r.draft.tipo,'pagamento_fatura');
console.log('PASS: cash/card separation, equal-day comparisons, zero baseline, closing dates, recurrence anchor and message review drafts.');
