import express from 'express';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import {randomBytes,randomUUID} from 'node:crypto';
import {hashPassword,checkPassword,digest} from './password.mjs';
export function createApp({pool,transaction}){
const app=express();app.disable('x-powered-by');app.set('trust proxy',Number(process.env.TRUST_PROXY||0));
app.use(helmet({contentSecurityPolicy:{directives:{'script-src':["'self'"],'style-src':["'self'","'unsafe-inline'"],'connect-src':["'self'"],'img-src':["'self'",'data:'],'upgrade-insecure-requests':process.env.NODE_ENV==='production'?[]:null}}}));
app.use(express.json({limit:'1mb'}));
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(req.headers.origin&&req.headers.origin!==process.env.APP_ORIGIN)return res.status(403).json({message:'Origem não autorizada.'});next();});
app.use('/api/auth',rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:true,legacyHeaders:false}));
const fail=(message,status=400)=>Object.assign(Error(message),{status});
async function issue(c,id){const token=randomBytes(32).toString('hex'),expires=Math.floor(Date.now()/1000)+43200;await c.query("delete from auth.sessions where expires_at<now()");await c.query('insert into auth.sessions values($1,$2,to_timestamp($3))',[digest(token),id,expires]);return {access_token:token,refresh_token:token,expires_at:expires,expires_in:43200,user:{id}};}
app.post('/api/auth/v1/token',async(req,res)=>{if(req.query.grant_type==='refresh_token'){const token=String(req.body.refresh_token||'');const r=await pool.query('select user_id from auth.sessions where token_hash=$1 and expires_at>now()',[digest(token)]);if(!r.rowCount)throw fail('Entre novamente.',401);const expires=Math.floor(Date.now()/1000)+43200;await pool.query('update auth.sessions set expires_at=to_timestamp($2) where token_hash=$1',[digest(token),expires]);return res.json({access_token:token,refresh_token:token,expires_at:expires,user:{id:r.rows[0].user_id}});}if(req.query.grant_type!=='password')throw fail('Operação inválida.');const email=String(req.body.email||'').trim().toLowerCase();const r=await pool.query('select id,password_hash from auth.users where lower(email)=$1',[email]);if(!await checkPassword(req.body.password,r.rows[0]?.password_hash))throw fail('E-mail ou senha inválidos.',401);res.json(await transaction(c=>issue(c,r.rows[0].id)));});
app.post('/api/auth/v1/signup',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),hash=await hashPassword(req.body.password);const session=await transaction(async c=>{const invite=await c.query('select * from public.fin_convites where token=$1 and lower(email)=$2 and not usado and expira_em>now() for update',[req.body.invite,email]);if(!invite.rowCount)throw fail('Convite inválido ou expirado.',403);const existing=await c.query('select id from auth.users where lower(email)=$1',[email]);if(existing.rowCount)throw fail('Esse e-mail já tem cadastro. Entre com sua senha.');const id=randomUUID();await c.query('insert into auth.users(id,email,email_confirmed_at,password_hash) values($1,$2,now(),$3)',[id,email,hash]);await c.query("select set_config('app.user_id',$1,true)",[id]);await c.query('select public.fin_aceitar_convite($1)',[req.body.invite]);return issue(c,id);});res.json(session);});
app.use('/api',async(req,res,next)=>{const token=(req.headers.authorization||'').replace(/^Bearer /,'');const r=await pool.query('select user_id from auth.sessions where token_hash=$1 and expires_at>now()',[digest(token)]);if(!r.rowCount)throw fail('Entre novamente.',401);req.user=r.rows[0].user_id;req.token=token;next();});
app.post('/api/auth/v1/logout',async(req,res)=>{await pool.query('delete from auth.sessions where token_hash=$1',[digest(req.token)]);res.json(null);});
const tables=new Set(['familias','pessoas','contas','cartoes','categorias','lancamentos','fin_subcategorias','fin_metas','fin_orcamentos','fin_movimentos','fin_planos','fin_convites']);
const writes=new Set(['contas','cartoes','categorias','fin_subcategorias','fin_metas','fin_orcamentos','fin_movimentos','fin_planos','fin_convites']);
const rpcs={fin_criar:['p_id','p_familia','p_modalidade','p_inicio','p_fim','p_frequencia','p_quantidade','p_dados'],fin_atualizar_recorrencias:[],fin_editar:['p_id','p_futuras','p_descricao','p_valor','p_pessoa','p_categoria','p_subcategoria','p_data','p_real'],fin_editar_compra:['p_id','p_futuras','p_descricao','p_valor','p_pessoa','p_categoria','p_subcategoria','p_data','p_real','p_compra'],fin_cancelar:['p_id','p_futuras'],fin_excluir:['p_id','p_escopo'],fin_confirmar_cobranca:['p_id','p_efetivada'],fin_versao_cartoes:[],fin_aceitar_convite:['p_token']};
app.post('/api/rest/v1/rpc/:name',async(req,res)=>{const keys=rpcs[req.params.name];if(!keys)throw fail('Função indisponível.',404);if(req.params.name==='fin_aceitar_convite'){// Signup has already consumed the capability; allow its subsequent boot retry.
 const found=await pool.query('select 1 from public.fin_convites c join public.pessoas p on p.id=c.pessoa_id where c.token=$1 and c.usado and p.usuario_id=$2',[req.body.p_token,req.user]);if(found.rowCount)return res.json('Acesso vinculado com sucesso');}
const result=await transaction(async c=>(await c.query(`select public.${req.params.name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as result`,keys.map(k=>req.body[k]??null))).rows[0].result,req.user);res.json(result);});
const columns=new Map();async function tableColumns(c,t){if(!columns.has(t))columns.set(t,new Set((await c.query("select column_name from information_schema.columns where table_schema='public' and table_name=$1",[t])).rows.map(x=>x.column_name)));return columns.get(t);}
app.all('/api/rest/v1/:table',async(req,res)=>{const t=req.params.table;if(!tables.has(t))throw fail('Tabela indisponível.',404);const result=await transaction(async c=>{const allowed=await tableColumns(c,t);const vals=[],where=[];for(const [key,value]of Object.entries(req.query)){if(['select','order','limit','offset','on_conflict'].includes(key))continue;if(!['id','familia_id','plano_id'].includes(key)||!allowed.has(key)||typeof value!=='string'||!value.startsWith('eq.'))throw fail('Filtro inválido.');vals.push(value.slice(3));where.push(`"${key}"=$${vals.length}`);}const filter=where.length?' where '+where.join(' and '):'';
if(req.method==='GET'){const limit=Math.min(500,Math.max(1,parseInt(req.query.limit)||500)),offset=Math.max(0,parseInt(req.query.offset)||0);return(await c.query(`select * from public.${t}${filter} order by id limit ${limit} offset ${offset}`,vals)).rows;}
if(!writes.has(t))throw fail('Operação não permitida.',403);
const clean=row=>{if(!row||typeof row!=='object'||Array.isArray(row))throw fail('Dados inválidos.');const keys=Object.keys(row);if(!keys.length||keys.some(k=>!allowed.has(k)))throw fail('Campo inválido.');return keys;};
if(req.method==='PATCH'){if(!where.length)throw fail('Selecione um registro.');const keys=clean(req.body);if(keys.some(k=>['id','familia_id','usuario_id'].includes(k)))throw fail('Campo protegido.',403);const set=keys.map(k=>{vals.push(req.body[k]);return `"${k}"=$${vals.length}`;});return(await c.query(`update public.${t} set ${set.join(',')}${filter} returning *`,vals)).rows;}
if(req.method==='POST'){const rows=Array.isArray(req.body)?req.body:[req.body];if(rows.length>500)throw fail('Lote grande demais.');const output=[];for(const row of rows){const keys=clean(row);const ignore=req.headers.prefer?.includes('resolution=ignore-duplicates');const r=await c.query(`insert into public.${t} (${keys.map(k=>'"'+k+'"').join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) ${ignore?'on conflict(id) do nothing':''} returning *`,keys.map(k=>row[k]));output.push(...r.rows);}return output;}
throw fail('Método não permitido.',405);},req.user);res.json(result);});
app.get('/health',async(req,res)=>{await pool.query('select 1');res.json({status:'ok'});});
app.use(express.static(new URL('../dist',import.meta.url).pathname,{index:'index.html',maxAge:0}));
app.use((err,req,res,next)=>{const status=err.status||(['42501'].includes(err.code)?403:err.code?.startsWith('23')||err.code==='P0001'||err.code==='22P02'?400:500);if(status===500)console.error('Erro no servidor:',err.code||err.name);res.status(status).json({message:status===500?'Erro interno. Consulte o administrador.':err.code==='P0001'?err.message:err.status?err.message:'Dados inválidos ou operação não permitida.'});});
return app;
}
