do $$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin; end if; if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if; end $$;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,password_hash text);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('app.user_id',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;
create table familias(id uuid primary key default gen_random_uuid(),nome text);create table pessoas(id uuid primary key default gen_random_uuid(),familia_id uuid references familias,usuario_id uuid unique references auth.users,nome text,unique(familia_id,id));create table categorias(id uuid primary key default gen_random_uuid(),familia_id uuid references familias,nome text,tipo text,ativa boolean default true,unique(familia_id,id,tipo));create table contas(id uuid primary key default gen_random_uuid(),familia_id uuid references familias,nome text,tipo text check(tipo in ('bancaria','dinheiro')),saldo_inicial numeric(14,2),data_saldo_inicial date,ativa boolean default true,unique(familia_id,id));create table cartoes(id uuid primary key default gen_random_uuid(),familia_id uuid references familias,nome text,principal boolean default false,dia_fechamento integer,dia_vencimento integer,ativo boolean default true,unique(familia_id,id));create table lancamentos(id uuid primary key default gen_random_uuid(),familia_id uuid,pessoa_id uuid,tipo text,descricao text,valor numeric(14,2),data_ocorrencia date,forma text,conta_id uuid,cartao_id uuid,categoria_id uuid);
create schema financeiro_privado;create function financeiro_privado.minhas_familias() returns setof uuid language sql stable security definer set search_path='' as $$ select familia_id from public.pessoas where usuario_id=auth.uid() $$;grant usage on schema financeiro_privado to authenticated;grant execute on function financeiro_privado.minhas_familias() to authenticated;grant select,insert,update on familias,pessoas,categorias,contas,cartoes to authenticated;

create table auth.sessions(token_hash text primary key,user_id uuid not null references auth.users(id) on delete cascade,expires_at timestamptz not null);
create index on auth.sessions(expires_at);
revoke all on schema auth from public;
revoke all on auth.users,auth.sessions from public,authenticated,anon;

create unique index users_email_unique on auth.users(lower(email));
